baseURL = "https://wmarquardt.com/"
title = "William Marquardt :: Back-End engineer :: Python :: Cloud :: Security :: Cats :: Drums"
subtitle = "William Marquardt"
theme = "m10c-mod"
paginate = 10
googleAnalytics = "UA-136426542-1"



[blackfriday]
  hrefTargetBlank = true

[menu]
  # [[menu.main]]
  #   identifier = "home"
  #   name = "Home"
  #   url = "/"
  #   weight = 1

  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 2

  #[[menu.main]]
  #  identifier = "home"
  #  name = "Home"
  #  url = "/"
  #  weight = 1

  #[[menu.main]]
  #  identifier = "posts"
  #  name = "Posts"
  #  url = "/posts/"
  #  weight = 2
  
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/cv/en/"
    weight = 4
  
  [[menu.main]]
    identifier = "songs"
    name = "Songs"
    url = "/songs/"
    weight = 5
  
[params]
  author = "William Marquardt"
  description = "I'm a husband, drummer, gamer, cat father, and also a software engineer"
  menu_item_separator = " | "
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#f5e3e0"
  #   lightestColor = "#f5f5f5"
  #   primaryColor = "#ffffff"

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/wmarquardt"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/williammqt/"
  
  #[[params.social]]
  #  icon = "whatsapp"
  #  name = "Whatsapp"
  #  url = "https://wa.me/5541984282865"
  
  [[params.social]]
    icon = "terminal"
    name = "Tryhackme"
    url = "https://tryhackme.com/p/wmarquardt"
  
  [[params.social]]
    icon = "python"
    name = "Pypi"
    url = "https://pypi.org/user/wmarquardt/"
  
  [[params.social]]
    icon = "spotify"
    name = "My band"
    url = "https://open.spotify.com/artist/1c1ikPGXD9ukA2utz9jx0a?si=R6WDvQxUTtW7UmLQvGuyoQ"
  
