baseURL = "/"
title = "William Marquardt"
theme = "m10c"
paginate = 8

# [params]
 
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"

[params]
  author = "William Marquardt"
  description = "I'm a fiance, drummer, gamer, cat father, and also software engineer"
  menu_item_separator = " | "
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#f5e3e0"
  #   lightestColor = "#f5f5f5"
  #   primaryColor = "#ffffff"

  [[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/vaga"

  [[params.social]]
    icon = "linkedin"
    name = "My Linkedin"
    url = "https://github.com/wmarquardt"
